server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: root-redirect
          uri: no://op
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /login
        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/dashboard, /dashboard/**, /api/services/status/**
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
            - SaveSession
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/login, /logout, /access-denied,
              /api/auth/**, /api/etablissements/**, /api/gammes/**, /api/users/**,
              /users/**, /profiles/**, /permissions/**,
              /products/**, /produits/**, /produit/**,
              /gammes/**,
              /etablissements/**, /etablissement/**,
              /depots/**,
              /zones/**,
              /h2-console/**
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
            - SaveSession

springdoc:
  swagger-ui:
    urls:
      - name: core-service
        url: /core-service/v3/api-docs
      - name: dashboard-service
        url: /dashboard-service/v3/api-docs

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    com.trace: INFO
